name: docker-amd
channels:
  - conda-forge
dependencies:
  - pip
  # scikit-image=0.18.1
  - openslide
  - zlib
  - jpeg
  - jbig
  - xz
  - zstd
  - libwebp-base  # [linux or osx]
  - numpy=1.22.0
  # - xorg-libxcb
  - python=3.8
  - cudatoolkit=11.2.0
  - cudatoolkit-dev=11.2
    #- cxx-compiler
    #- c-compiler
  - cmake
  - automake
  - make
  - click
  - yasm # [x86_64]
  - isort
  - flake8
  # amd-test requirements
  - jupyterlab
  - matplotlib
  # cupy=10.0.0
  # scikit-learn requirements
  - cython
  - compilers
  - openblas
  - lapack
  - llvm-openmp
  - threadpoolctl
  - joblib
  # scipy requirements
  - libblas=*=*openblas
  - pybind11
  - pythran>=0.9.12
  - pytest
  - pytest-cov
  - pytest-xdist
  - asv
  - conda-build
  - mypy
  - typing_extensions
  - mpmath
  - gmpy2=2.1.0rc1
  # scipy
  - meson
  - ninja
  # scikit-learn
  - pkg-config
  # numpy requirements
  - nomkl
  - numpy
  - setuptools=59.2.0
  - tifffile
  - tqdm
