name: Build Environment

on: [push]

jobs:
  build:
    runs-on: "self-hosted"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        env:
          CONDA: /work/aktech/miniconda3
        with:
          activate-environment: amd-github-env
          environment-file: environment.yml
          auto-activate-base: false
          condarc-file: /work/aktech/.condarc

      - name: conda info
        run: |
          conda info
          conda list

      - name: Nvidia-SMI
        run: |
          nvidia-smi
